services:
  db:
    image: mysql:5.7
    container_name: mysql5
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mudar123
      MYSQL_DATABASE: teste
      MYSQL_USER: app
      MYSQL_PASSWORD: app123
    ports:
      - "3307:3306"   # host:container (para conectar externamente no 3307)
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-pmudar123"]
      interval: 10s
      timeout: 5s
      retries: 10

  web:
    build:
      context: ./web
    container_name: python-web
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      DB_NAME: teste
      DB_USER: app
      DB_PASSWORD: app123
      SECRET_KEY: troque-isto
      FLASK_ENV: production
    ports:
      - "5050:5050"
    depends_on:
      db:
        condition: service_healthy

  adminer:
    image: adminer:4
    container_name: adminer
    restart: unless-stopped
    depends_on:
      db:
        condition: service_started
    ports:
      - "8080:8080"

volumes:
  db_data:
